# step 4.1 Final Cleaning
prepering the df for the model.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("final_df_with_fabric_vectors.csv")

## Categorical columns

טיפול בעמודות קטגוריאליות, קטגוריזציה של עמודות קטגוריאליות כמו עמודת המותג, והורדת עמודות שלא ניתן לקטרג כמו עמודת השם, מספר הזיהוי ותרכובת הבד

In [4]:
brand_normalized=[]

for row in df.brand:
    if row=="shopbop":
        brand_normalized.append(1)
        
    if row=="avenue":
        brand_normalized.append(2)
        
df.brand=brand_normalized  
df

,brand,product_names,prices,ids,ratings,fabrics,category,XXS,XS,S,...,mesh,midweight,nonstretch,nylon,polyester,poplin,satin,stretch,viscose,weave
0,1,Lace Top,490.000000,PACOO30471,0,"Lightweight, stretch lace",Tops,0,1,1,...,0,0,0,0,0,0,0,1,0,0
1,1,Jupe Skirt,620.000000,PACOO30468,0,"Lightweight, stretch floral lace",Skirts,0,1,1,...,0,0,0,0,0,0,0,1,0,0
2,1,Wyatt Shirt,255.000000,RAGBO46380,0,"Midweight, nonstretch denim",Tops,0,0,1,...,0,1,1,0,0,0,0,0,0,0
3,1,Shelly Wide Leg Crepe Pants,475.000000,RAGBO46413,0,Midweight stretch crepe,Pants,0,1,1,...,0,1,0,0,0,0,0,1,0,0
4,1,Jylan Moto Jacket,1598.000000,VBEAR32197,0,"Heavyweight, nonstretch leather",Jackets_Coats,0,1,1,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11444,2,High Rise Jegging Mid Wash - petite,9.000000,207172PTMDWS,3,"78% Cotton, 20% Polyester, 2% Elastane.",Pants,0,0,0,...,0,0,0,0,1,0,0,0,0,0
11445,2,High Rise Jegging Dark Wash - petite,19.990000,207172PTDKWS,3,"78% Cotton, 20% Polyester, 2% Elastane.",Pants,0,0,0,...,0,0,0,0,1,0,0,0,0,0
11446,2,Luxe Cool Hand Slimming Pant Gray - average,23.712277,204374480GREYAVERAGE,4,"72% Polyester, 24% Rayon, 4% Spandex. Fabric h...",Pants,0,0,0,...,0,0,0,0,1,0,0,1,0,0
11447,2,Wonderwall Coat - black,52.880936,138764BLACK,5,"Main: 95% Polyester, 4% Viscose, 1% Nylon. Lin...",Jackets_Coats,0,0,0,...,0,0,0,1,1,0,0,0,1,0
11448,2,Butter Denim Skinny Jean Black - petite,34.500000,214246PTBLK,0,"76% Cotton, 23% Polyester, 1% Elastane. Fabric...",Pants,0,0,0,...,0,0,0,0,1,0,0,1,0,0

In [5]:
category_dict={1:'Dresses', 2:'Jackets_Coats', 3:'Jumpsuits_Rompers', 4:'Lingerie', 5:'Maternity', 6:'Pants',
              7:'Skirts', 8:'Sleepwear', 9:'Sweaters_Knits', 10:'Swimsuits_Cover_Ups', 11:'Tops'}
normalized_categorys=[]

for row in df.category:
    if row=='Dresses': normalized_categorys.append(1)
    if row=='Jackets_Coats': normalized_categorys.append(2)    
    if row=='Jumpsuits_Rompers': normalized_categorys.append(3)
    if row=='Lingerie': normalized_categorys.append(4)    
    if row=='Maternity': normalized_categorys.append(5)    
    if row=='Pants': normalized_categorys.append(6)    
    if row=='Skirts': normalized_categorys.append(7)  
    if row=='Sleepwear': normalized_categorys.append(8)   
    if row=='Sweaters_Knits': normalized_categorys.append(9)    
    if row=='Swimsuits_Cover_Ups': normalized_categorys.append(10)    
    if row=='Tops': normalized_categorys.append(11)
        
df["category"]=normalized_categorys

In [6]:
df_non_cat=df.copy()
df_non_cat.to_csv("dataset_for_model.csv", index=False)
df_non_cat.drop(["fabrics","product_names","ids"], inplace=True, axis=1)
df_non_cat

,brand,prices,ratings,category,XXS,XS,S,P,M,L,...,mesh,midweight,nonstretch,nylon,polyester,poplin,satin,stretch,viscose,weave
0,1,490.000000,0,11,0,1,1,0,1,0,...,0,0,0,0,0,0,0,1,0,0
1,1,620.000000,0,7,0,1,1,0,1,0,...,0,0,0,0,0,0,0,1,0,0
2,1,255.000000,0,11,0,0,1,0,1,1,...,0,1,1,0,0,0,0,0,0,0
3,1,475.000000,0,6,0,1,1,0,1,0,...,0,1,0,0,0,0,0,1,0,0
4,1,1598.000000,0,2,0,1,1,0,1,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11444,2,9.000000,3,6,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
11445,2,19.990000,3,6,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
11446,2,23.712277,4,6,0,0,0,0,0,1,...,0,0,0,0,1,0,0,1,0,0
11447,2,52.880936,5,2,0,0,0,0,0,1,...,0,0,0,1,1,0,0,0,1,0
11448,2,34.500000,0,6,0,0,0,0,0,1,...,0,0,0,0,1,0,0,1,0,0

## Continuous variable
טיפול במשתנים רציפים כמו עמודת המחיר, נירמול של העמודה.

In [7]:
# df on input should contain only one column with the price data (plus dataframe index)
# return: y will be a column in a dataframe
def normalize_col(df):
    min = df.min()
    max = df.max()
    x = df 
    y = (x - min) / (max - min)
    
    return y

In [8]:
df_non_cat['norm_prices']= normalize_col(df_non_cat.prices)
df_non_cat['norm_prices']

0        0.121400
1        0.153987
2        0.062492
3        0.117640
4        0.399143
           ...
11444    0.000827
11445    0.003582
11446    0.004515
11447    0.011827
11448    0.007219
Name: norm_prices, Length: 11449, dtype: float64

In [9]:
df_non_cat.drop(["prices"], inplace=True, axis=1)
df_non_cat

,brand,ratings,category,XXS,XS,S,P,M,L,XL,...,midweight,nonstretch,nylon,polyester,poplin,satin,stretch,viscose,weave,norm_prices
0,1,0,11,0,1,1,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0.121400
1,1,0,7,0,1,1,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0.153987
2,1,0,11,0,0,1,0,1,1,0,...,1,1,0,0,0,0,0,0,0,0.062492
3,1,0,6,0,1,1,0,1,0,0,...,1,0,0,0,0,0,1,0,0,0.117640
4,1,0,2,0,1,1,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0.399143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11444,2,3,6,0,0,0,0,0,1,1,...,0,0,0,1,0,0,0,0,0,0.000827
11445,2,3,6,0,0,0,0,0,1,1,...,0,0,0,1,0,0,0,0,0,0.003582
11446,2,4,6,0,0,0,0,0,1,1,...,0,0,0,1,0,0,1,0,0,0.004515
11447,2,5,2,0,0,0,0,0,1,1,...,0,0,1,1,0,0,0,1,0,0.011827
11448,2,0,6,0,0,0,0,0,1,1,...,0,0,0,1,0,0,1,0,0,0.007219

In [10]:
df_non_cat.to_csv("finale_normalized_df.csv", index=False)